---
- name: AWS Infrastucture using Ansible 
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
  - aws_infra_ansible



- name: Install JBoss and Deploy Apps
  hosts: new_host
  become: true
  roles:
    - jboss-standalone
    - java-app
