---
- name: AWS Infrastucture using Ansible 
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
  - { role: aws_infra_ansible, vpc_state: 'create' }



- name: Install JBoss and Deploy Apps
  hosts: new_host
  become: true
  roles:
    - jboss-standalone
    - java-app
